version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=email_system

  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    command: rabbitmq-server
    env_file: .env
    ports:
        - 5673:5672
        - 15672:15672
    volumes:
      - 'rabbit_data:/data'

  worker:
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    command: celery -A emailsystem worker -l info"
    volumes:
        - worker_data:/app
    links:
        - rabbit
    depends_on:
        - rabbit
    env_file: .env
  
volumes:
  postgres_data:
  rabbit_data:
  worker_data:
